# Secrets: -

name: "Godot CD Preview on PR"

env:
  GODOT_VERSION: 4.4.1
  PROJECT_NAME: 'ci_example'

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
      - review_requested
      - review_request_removed
      - converted_to_draft

jobs:
  Web:
    if: >
      ${{
        !contains(github.event.head_commit.message, '[skip ci]') &&
        (
          contains(github.event.comment.body, 'Deploy') ||
          contains(github.event.comment.body, 'deploy') ||
          github.event_name == 'push' ||
          github.event_name == 'pull_request'
        )
      }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: barichello/godot-ci:4.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          lfs: true

      - name: Move export templates into position
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Create staging directory
        run: mkdir -v -p build/web
        
      - name: Import assets
        run: |
          godot --import --headless
          # Run a second time to make sure that the warnings have cleared.
          # This should exit pretty much immediately.
          godot --import --headless

      - name: Build
        run: godot -v --export-release --headless "Web"

      - name: Add coi-service-worker
        run: |
          git clone https://github.com/gzuidhof/coi-serviceworker.git
          mv coi-serviceworker/coi-serviceworker.js build/web/coi-serviceworker.js
          sed -i '3 i <script src="coi-serviceworker.js"></script>' build/web/index.html

      - name: 🚀 Deploy to `gh-pages` branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
          keep_files: true
          user_name: "github-ci[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "Deploy PR web deploy to subdirectory ${{ github.event.number }}"
          destination_dir: ${{ github.event.number }}
      
  PR-comment-update:
    needs: [Web]
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write 
    if: always()
    steps:
      - name: Set preview URL message
        id: set-message
        run: |
          if [[ "${{ needs.Web.result }}" == "success" ]]; then
            echo "message=🌐 [Web Preview](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.event.pull_request.number }}/)" >> $GITHUB_OUTPUT
          else
            echo "message=❌ Deployment failed for this PR." >> $GITHUB_OUTPUT
          fi

      - name: Comment deploy preview URL
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: ${{ steps.set-message.outputs.message }}
          comment-tag: execution